# Generated by Django 4.2.14 on 2024-07-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("cover", models.FilePathField()),
                ("desc", models.CharField(max_length=1000)),
                ("online", models.BooleanField()),
            ],
        ),
    ]
