# Generated by Django 4.2.14 on 2024-07-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.FilePathField(path="/website/images"),
        ),
    ]
