# Generated by Django 4.2.14 on 2024-07-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_project_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.FilePathField(path="{% static 'website/images' %}"),
        ),
    ]
