# Generated by Django 4.2.14 on 2024-09-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_alter_project_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="online",
        ),
        migrations.AddField(
            model_name="project",
            name="site",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.FilePathField(path="website/static/website/images"),
        ),
    ]
