# Generated by Django 4.2.14 on 2024-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_remove_project_online_project_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="cover",
            field=models.FilePathField(path="website\\static\\website\\images"),
        ),
    ]
