# Generated by Django 4.2.14 on 2024-09-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_alter_project_cover"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="cover",
        ),
    ]
